name: megaworkflow

on:
  workflow_dispatch:

# https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow
# https://docs.github.com/en/actions/using-workflows/reusing-workflows#example-caller-workflow
jobs:
  call-reusable-one:
    uses: ./.github/workflows/reusable-one.yml  # cannot specify version if calling local workflow.
  call-reusable-two:
    uses: sjspielman/tasty/.github/workflows/reusable-two.yml@main # with path for a PUBLIC repo, can specify version

# if we need secrets: https://docs.github.com/en/actions/using-workflows/reusing-workflows#passing-inputs-and-secrets-to-a-reusable-workflow
