name: Manually trigger issue creation for standard set up

# This is a manually triggered workflow
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
# https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#running-a-workflow-on-github
on:
  workflow_dispatch:
  workflow_call:


jobs:
  # This runs a single job that creates issues from files
  createIssuesFromFile:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Check out
      - uses: actions/checkout@v3

      # Issue for turning on GitHub pages
      - name: Create GitHub Pages issue
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          title: Turn on GitHub Pages
          content-filepath: ./setup-issue-templates/gh-pages.md
          labels: automated training issue
