name: Manually trigger issue creation for standard set up

# This is a manually triggered workflow
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_dispatch
# https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow#running-a-workflow-on-github
on:
  workflow_dispatch:

jobs:
  # This runs a single job that creates issues from files
  createIssuesFromFile:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Check out
      - uses: actions/checkout@v3


      # Issue for turning on branch protection
      - name: Create branch protection issue
        uses: peter-evans/create-issue-from-file@v4.0.0
        with:
          title: Set up branch protection - pull requests required
          content-filepath: ./setup-issue-templates/branch-protection.md
          labels: automated training issue
